### ISSUE TITLE
Remove the pinyin from the 'meanings' field

### ISSUE THREAD

**Issue by jonamun** [krmanik/Anki-xiehanzi#14]
Hi, I messaged you on Reddit.

I was wondering if it's possible to remove the pinyin from 'meanings' field since there already is a pinyin field and I don't want to see the pinyin when testing my recall. Card type 1 is already possible but I can't set up card type 2.

**Card type 1** (testing my reading): 
Front (hanzi) --- > Back (pinyin, meaning, audio) 
**Card type 2** (to test my recall):
 Front (meaning) --> Back (hanzi, pinyin, audio)

**Comment by krmanik** [comment]
It is possible to create this. I will update the new TSV files for this.

**Comment by krmanik** [comment]
I hope it will solve the issue, view this page.
[Create new decks with customized templates](https://github.com/krmanik/Anki-xiehanzi/blob/master/Create%20new%20deck%20with%20customised%20templates.md)

**Comment by jonamun** [comment]
This has solved my issue, thank you so much!

I have one question. It's more Anki related. Is there any way to change the order of the cards? It's starting in alphabetical so all the words sound the same to me.

**Comment by krmanik** [comment]
It needs to be sorted using [frequency order](https://github.com/krmanik/HSK-3.0-words-list/blob/main/Scripts%20and%20data/freq_sim.txt) (more frequency order can find online) using python script.

May be I will update it in order later.
```python
with open('HSK Meaning/Separate Pinyin/HSK 1.tsv', 'r', encoding='utf-8') as fin:
    d = dict(x.split(None, 1) for x in fin)

added=[]
with open('freq_sim.txt', 'r', encoding='utf-8') as fin, open('output', 'w', encoding='utf-8') as fout:
    for line in fin:
        key = line.split()[1]
        try:
            if key not in added:
                #print(key, d[key])
                added.append(key)
                fout.write(d[key])
        except KeyError:
            pass
```

**Comment by jonamun** [comment]
Ah okay :(, I ran the script but a lot of the HSK characters are missing. Frequency would be really good for a future iteration. Thanks for your help!
