### ISSUE TITLE
Pinyin should not be present in {{Meaning}} field.

### ISSUE THREAD

**Issue by AXiSource** [krmanik/Anki-xiehanzi#16]
I think the destination of the field should be respected.

I would like to customize this deck but the presence of pinyin in the meaning field makes it tedious (I don't use pinyin but zhuyin)

If you want to display Pinyin I think it would be better to use the {{Pinyin}} field.

Thanks for sharing anyway.
It's nice to have a high quality deck with the new HSK.

**Comment by krmanik** [comment]
Zhuyin is coming soon to xiehanzi v2 deck. I have created deck with zhuyin and pinyin. It will be released in 2-3 days here and on ankiweb.

**Comment by krmanik** [comment]
The latest deck have option to show and hide pinyin or zhuyin.
