### ISSUE TITLE
Drawing pad not showing in both latest (tone-colored strokes) versions

### ISSUE THREAD

**Issue by camerooncameroon** [krmanik/Anki-xiehanzi#23]
Great update, thanks for your outstanding work!
Tone colored strokes are unbelievably useful.
The screenshots are really cool!

Although, I downloaded latest version and previous, both seem not to display drawing pad at all. 

Old versions (not-colored strokes) are working fine.

**Comment by camerooncameroon** [comment]
![image](https://user-images.githubusercontent.com/78047188/193650098-4585d7f2-afd8-4baf-b933-77278a92dea5.png)

**Comment by krmanik** [comment]
Install this addon to inspect the webview. After install/restart Anki, right click and inspect the above current notes and paste screenshot here. I have checked it again but no issues. The inspect webview may tell something about the issues.

AnkiWebView Inspector
https://ankiweb.net/shared/info/31746032

Similar to this image.
![image](https://user-images.githubusercontent.com/12841290/193655797-51770bc4-d1e2-4274-ba5e-a639071c9390.png)

**Comment by camerooncameroon** [comment]
I'll do as you instruct and put the resulting screenshot promptly.
Also, I guess it's worth mentioning that the same situation occurs also on AnkiDroid (as well as on Anki Desktop windows version)

**Comment by camerooncameroon** [comment]
Also some screenshots from Android：
![image](https://user-images.githubusercontent.com/78047188/193778007-19f2e515-c014-42e5-af56-854fe6e2e034.png)
![image](https://user-images.githubusercontent.com/78047188/193778044-817c9e3f-a96b-44b7-bfce-4daa1dc03bd1.png)

**Comment by krmanik** [comment]
I have released the fix. The latest version can be used. The issue is that lower version of Anki does not support `localStorage` so I have used [anki-persistence](https://github.com/SimonLammer/anki-persistence) for that.

**Comment by camerooncameroon** [comment]
@krmanik 
Downloaded the updated version, now everything is cool.
Thank you!
One small question, not an issue to open new thread:
can the drawing color be also tone-specific? (now black/white)
You know, like you are using colored ink to draw...
So that the drawing and stroke colors are identical.
Perhaps you can publish a snippet of code to replace or a howto-hint, not to change the release if you don't find it useful
