### ISSUE TITLE
Changes in sidebar (hint before misses, stroke width) has no effect on appearance and behaviour, + keyboard doesn't popup, have to paste

### ISSUE THREAD

**Issue by camerooncameroon** [krmanik/Anki-xiehanzi#27]
**Describe the bug**
Changes in sidebar (hint before misses, stroke width) has no effect on appearance and behaviour, + keyboard doesn't popup on tap on field, have to write elsewhere then copy-paste.
**To Reproduce**
1. On Ankidroid, open sidebar.
2. Click on 'hint before misses', ‘stroke width'.
3. No keyboard appears.
4. Write the desired numbers elsewhere, then copy-paste.
5. After inputting altered parameters, the width and erroneous tries before hint stay the same.

**Expected behavior**
Keyboard pops up, on entering altered numbers stroke width and tries before hint shall also alter in prescribed ways.

Desktop (please complete the following information):

Desktop OS Windows 10.
Browser Edge.
Anki version Version ⁨2.1.49 (dc80804a)⁩ Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Smartphone (please complete the following information):

Samsung Galaxy Note 4 SM 9100 N.
OS: Android 6.0.1.
Browser: stock browser.
Version: AnkiDroid 2.15.6.

**Comment by krmanik** [comment]
The fix will be available after merge of the PR and the keyboard can be shown with enabling type in card features.
```
AnkiDroid -> Settings -> Advanced -> Type answer into the Card
```

**Comment by krmanik** [comment]
@camerooncameroon 
Your feedbacks are very helpful. I will create release after testing it on other devices. 
Please extract the zip file and test if issues resolved or not.
[Anki xiehanzi__HSK 1.zip](https://github.com/krmanik/Anki-xiehanzi/files/9727345/Anki.xiehanzi__HSK.1.zip)

**Comment by camerooncameroon** [comment]
@krmanik 
Hi, you're always welcome! Your quiz cards are fantastic!
Sorry I missed your comment, will try it and report back here.
The bug displayed in this thread's title still persists in latest to date version of Hsk deck (can't change hints before misses, stroke width parameters etc in sidebar on Android 6.0.1 + still no keyboard pops out, perhaps that's because of outdated Android version, all is well on Anki Desktop).
