### ISSUE TITLE
Make 'blink' in the end of quiz the same color as the hanzi just entered

### ISSUE THREAD

**Issue by camerooncameroon** [krmanik/Anki-xiehanzi#31]
**Is your feature request related to a problem? Please describe.**
After you enter a hanzi in quiz field, the hanzi kinda 'blinks' in blue color.
If you use colored hanzi, any other color can spoil the color accelerated memorization process.

**Describe the solution you'd like**
Remove this final blink or make it the same color as the hanzi just entered.

**Describe alternatives you've considered**
None.

**Additional context**
The 'blink' can be seen on this project's main page animated screenshots.

**Comment by krmanik** [comment]
I have added it to to-do list (In the weekend I will start on development). 
Thanks, for feedbacks.
