### ISSUE TITLE
Not to remove the last hanzi after entered (to better memorize) + avoid stretched writing pad in case of missing sound file

### ISSUE THREAD

**Issue by camerooncameroon** [krmanik/Anki-xiehanzi#32]
**Is your feature request related to a problem? Please describe.**
Feature proposal not a bug, only visual/cosmetic/effectiveness enhancements are needed

**Describe the solution you'd like**
Now after entering hanzi it disappears along with the writing pad itself (or, if there's no sound file, the hanzi disappears but the writing pad stays but in stretched/distorted way.
The solution I'd like is to keep the last (or the only) hanzi in anki card on even after entering to help better memorizing it. Also please allow to have Audio field empty but without distorted writing pad which appears in this case.

**Describe alternatives you've considered**
I used to fill Audio field with a nosoundfile.mp3 text in case of no real sound file which helped to avoid stretched writing pad. But this prevented TTS tags to speak up (because Audio field was not empty even though filled with a fake filename).

**Additional context**
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-11-05 13:56:11
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['reviewer_progress_bar', 0, 'None', '']
    Add Hyperlink ['318752047', 2021-11-21T21:04, 'None', '']
    Add a tag to notes with missing media ['2027876532', 2022-06-05T05:28, 'None', '']
    Add note id ['1672832404', 2020-12-06T15:44, 'None', '']
    Advanced Browser ['874215009', 2022-09-27T05:28, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-05-03T23:46, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2022-09-29T18:31, 'None', mod]
    Anki IPA ['799647424', 2022-10-23T21:26, 'None', mod]
    Anki Simulator ['817108664', 2021-08-08T00:24, 'None', '']
    AnkiConnect ['2055492159', 2022-09-19T05:11, 'None', '']
    AnkiWebView Inspector ['31746032', 2022-04-09T00:44, 'None', '']
    Answer Confirmation for 21 ['1354051622', 2019-04-04T17:54, 'None', '']
    Automatic Scoring 2 sets the focus easy good hard again based on time ['238560501', 2019-12-17T19:42, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2022-02-20T08:23, 'None', '']
    Basic Printing Support ['1025789669', 2022-03-04T16:14, 'None', '']
    Batch Editing ['291119185', 2019-06-02T23:47, 'None', '']
    Batch Remove Formatting eg bold italics etc ['1734822644', 2018-09-24T20:34, 'None', '']
    BetterSearch ['1052724801', 2021-11-21T23:42, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-26T03:11, 'None', '']
    CC-CEDICT for Anki Chinese dictionary ['418828045', 2022-03-23T17:22, 'None', mod]
    Chinese Companion - frequency sort HSK suspend heisig support and more ['2129668097', 2018-11-22T18:55, 'None', '']
    Chinese Prestudy ['882364911', 2020-11-03T11:43, 'None', mod]
    Chinese Support Redux v0142 ['1128979221', 2021-03-29T07:19, 'None', mod]
    Chinese Vocabulary Generator ['1370756741', 2021-02-24T13:07, 'None', '']
    Chinese Words Finder ['2048169015', 2020-07-07T17:32, 'None', mod]
    Chinese-Text-Scanner ['2121493325', 2020-06-28T09:53, 'None', mod]
    Clickable Tags v20 ['1739176371', 2022-01-31T03:58, 'None', '']
    Colorful Browser Sidebar ['929609616', 2021-09-09T23:03, 'None', mod]
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T20:06, 'None', '']
    Copy notes ['1566928056', 2021-12-25T00:56, 'None', '']
    Countdown To Events and Exams ['1143540799', 2021-03-14T01:40, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2022-07-28T18:54, 'None', mod]
    Deck name in title 21 ['699175524', 2019-06-01T06:05, 'None', '']
    Duplicate Selected Notes ['2126361512', 2017-08-29T23:57, 'None', '']
    Enhanced Cloze for Anki 21 ['1990296174', 2022-07-21T14:41, 'None', '']
    External Note Editor for the Browser ['1996266159', 2020-04-01T01:59, 'None', '']
    Fastbar- with nightmode support ['46611790', 2022-04-15T08:04, 'None', '']
    Find and Replace in Card templatesNotetypesHTML ['992153575', 2021-09-17T11:34, 'None', '']
    Flexible Cloze ['1632356464', 2022-10-16T16:30, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T22:06, 'None', '']
    Image Editor ['307397307', 2022-09-08T09:09, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T07:21, 'None', '']
    Image Style Editor ['1593969147', 2021-12-17T12:01, 'None', mod]
    ImageResizer ['1214357311', 2022-07-15T18:05, 'None', '']
    Load Balanced Scheduler ['208879074', 2018-10-05T05:06, 'None', '']
    Localize Media ['1293255374', 2018-11-26T16:27, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T22:45, 'None', '']
    Minimize to tray ['85158043', 2021-12-13T21:59, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T17:05, 'None', '']
    More Overview Stats ['2116130837', 2021-05-29T16:24, 'None', '']
    Papercards - export  print flashcards to paper ['2042118948', 2021-05-14T06:58, 'None', mod]
    Postpone cards review ['1152543397', 2021-02-13T21:47, 'None', '']
    Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-20T09:40, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T19:14, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T18:23, 'None', '']
    Search Bar ['1251668918', 2020-09-10T02:55, 'None', '']
    Search and Replace Tags ['138501288', 2017-08-29T23:58, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2021-09-17T15:24, 'None', mod]
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-20T02:32, 'None', mod]
    Sentence adder for any language with batch add option ['1682655437', 2022-06-16T16:30, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-12T16:47, 'None', '']
    True Retention ['613684242', 2017-11-20T01:43, 'None', '']
    Zoom 21 ['1846592880', 2020-01-12T22:26, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2021-12-06T01:28, 'None', '']
    extended editor for field for tables searchreplace ['805891399', 2022-03-13T15:51, 'None', '']
    remove linebreaks  do word wrap ['2028179508', 2022-09-28T19:20, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1025789669 1052724801 1128979221 1136455830 1143540799 1152543397 1210908941 1214357311 1251668918 1293255374 1354051622 1370756741 1374772155 138501288 1436550454 1556734708 1566928056 1593969147 1632356464 1642550423 1672832404 1682655437 1734822644 1739176371 1781298089 1810938259 1846592880 1898445115 1906641654 1990296174 1996266159 2027876532 2028179508 2042118948 2048169015 2055492159 208879074 2116130837 2121493325 2126361512 2129668097 225180905 238560501 291119185 295889520 307397307 31746032 318752047 418828045 46611790 561945101 594329229 613684242 668156440 699175524 799647424 805891399 817108664 831846358 85158043 874215009 882364911 929609616 992153575
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Cards - Web Browser ['1783260740', 2020-10-28T11:35, 'None', '']
    AddonBackup ['162231225', 2019-01-16T12:53, 'None', '']
    Advanced Answer Sounds ['1167194350', 2022-05-29T12:30, 'None', mod]
    Advanced Card Styles ['1625103157', 2021-09-23T16:51, 'None', '']
    Anki Excel Sync ['1832015432', 2021-01-28T08:53, 'None', '']
    Asset Manager ['656021484', 2021-08-30T02:07, 'None', '']
    Audio Files ['1984823157', 2022-07-30T19:20, 'None', mod]
    Automatic Basic to Cloze Updated ['800723229', 2022-07-11T17:12, 'None', '']
    Automatic Scoring sets the default grade easy good hard again based on time ['1765221856', 2020-05-04T11:21, 'None', '']
    Bury Cousins related cards that arent siblings ['1072815885', 2021-07-20T06:23, 'None', '']
    Bury related notes ['413416269', 2020-04-03T12:55, 'None', '']
    Button Colours Good Again ['2494384865', 2021-04-06T19:57, 'None', '']
    CSS Injector - Change default editor styles ['181103283', 2022-05-28T18:57, 'None', '']
    CTRLF5 to Refresh the Browser ['1347728560', 2019-07-30T11:36, 'None', '']
    Card Info During Review ['2179254157', 2021-02-05T15:22, 'None', '']
    Change Card Creation Times ['217650262', 2019-03-05T07:59, 'None', '']
    Change Order of Review Cards in Regular Decks ['3731265543', 2018-10-13T03:47, 'None', '']
    Chinese Getter ['972150718', 2021-06-23T19:27, 'None', '']
    Chinese Pinyin Translator Zhuyin Bopomofo Gwoyeu Romatzyh ['1792056402', 2018-11-09T08:27, 'None', mod]
    Closet For Anki ['272311064', 2021-04-12T19:09, 'None', '']
    Cloze Anything ['330680661', 2021-12-09T12:34, 'None', '']
    Cloze Hide All ['1709973686', 2021-09-11T15:00, '21.9.11i107', mod]
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-12T08:12, 'None', '']
    Color Confirmation ['1084228676', 2020-03-14T17:13, 'None', mod]
    Create Filtered Deck from the Browser ['861263371', 2017-08-29T23:57, 'None', '']
    Customize Editor Stylesheet ['1215991469', 2018-09-04T20:03, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-06-29T11:13, 'None', '']
    Duplicate and Reorder ['1114271285', 2022-06-30T02:04, 'None', '']
    Duplicate and Reorder ['duplicate_and_reorder', 2020-10-16T21:56, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2022-06-27T14:48, '6.13', mod]
    Export in CSV format ['1478130872', 2019-01-21T23:21, 'None', '']
    Extended Card Stats During Review ['1008566916', 2017-08-29T23:59, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2022-03-13T15:41, 'None', '']
    Fanfare ['2073603704', 2020-04-01T12:21, 'None', '']
    Fast cards reposition ['544982740', 2021-09-19T18:51, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2021-08-06T00:38, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2022-07-13T19:09, 'None', mod]
    Incremental Reading v4103 ['935264945', 2019-04-21T17:54, 'None', '']
    Legacy Remove HTML ['1101026246', 2021-01-25T00:40, 'None', '']
    Let it Snow ['321075516', 2017-12-21T21:48, 'None', '']
    Maximum image height and width in card editor ['229181581', 2021-07-23T11:01, 'None', '']
    MorphMan for Anki 21 ['900801631', 2022-01-30T03:23, 'None', '']
    Multi-column note editor ['3491767031', 2021-11-02T20:18, 'None', '']
    Multiple Choice for Anki ['1566095810', 2022-11-01T00:52, 'None', '']
    New Format Pack ['1187194862', 2021-08-10T05:41, 'None', '']
    Persistent Editor ['1686259334', 2021-02-12T05:05, 'None', '']
    Quick Colour Changing ['2491935955', 2022-07-24T09:29, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T19:14, '20.12.13i151', mod]
    Reset Card Scheduling ['300884351', 2018-09-18T21:17, 'None', '']
    Reset review log ['1345711295', 2020-06-05T12:03, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T11:35, 'None', mod]
    Review First ['181194973', 2019-03-06T22:47, 'None', '']
    Scale Images ['1312865748', 2022-04-19T23:59, 'None', '']
    Special Fields ['1102281552', 2022-02-23T22:27, 'None', '']
    Speed Focus Mode ['speed_focus_mode', 2019-06-29T03:35, 'None', '']
    TagSelectorV2 ['1022577188', 2021-08-07T16:28, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-18T03:33, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-08-03T01:49, 'None', '']
    blank ['1690290745', 2021-05-04T16:04, 'None', '']
    maobi - Chinese Hanzi Writing Quizzes in Anki v0 5 2 ['931477147', 2021-02-21T22:14, 'None', mod]
    show new siblings in order  no same day spacingrandomization for new siblings ['268644742', 2020-02-18T23:41, 'None', '']

**Comment by krmanik** [comment]
The issues are fixed but if it still happen then re-open the issue.
