### ISSUE TITLE
[Question] [Card 5]How do I change the colouring of the tones?

### ISSUE THREAD

**Issue by FancyFoxPerson** [krmanik/Anki-xiehanzi#34]
I figured out how to change the colours in the drawing box of Card 5 by adapting the style like this:
```
            case "char-tone1": return "#f44336";
            case "char-tone2": return "#02B31C";
            case "char-tone3": return "#1510F0";
            case "char-tone4": return "#8900BF";
```
(Those are the Pleco tone colours)
But the original colours still persist in the character at the top of the {Meaning} field. How can I change those, if possible at all?

**Comment by krmanik** [comment]
Read more here
https://krmanik.github.io/Anki-xiehanzi/docs/customization/change-tone-color
