### ISSUE TITLE
Small bug in UI - "what is the meanings?" should be "what is the meaning?"

### ISSUE THREAD

**Issue by jaanli** [krmanik/Anki-xiehanzi#35]
![image](https://user-images.githubusercontent.com/5317244/216779951-0e20ca71-c15c-48a1-b5f2-2a9030a641d7.png)

**Comment by krmanik** [comment]
I have used meanings because it may have multiple meanings. The meaning(s) can also be used here. It can be edited from card template editor.

**Comment by altosaar** [comment]
Got it! If "meanings", then it should read "What are the meanings?" instead of "What is the meanings?" Just a small grammar issue :) thank you so much for this!!
