### ISSUE TITLE
Menu Icons not loading

### ISSUE THREAD

**Issue by bbquetzl** [krmanik/Anki-xiehanzi#37]
The icons for the play and menu buttons don't seem to load. 
![image](https://user-images.githubusercontent.com/129011880/227808697-d98f37a8-0eea-438c-ba82-9346eb137ef3.png)

**Comment by krmanik** [comment]
Hi,

You have to download this three icons file and paste it in AnkiDroid/collection.media folder. The deck export from Ankiweb should have icons files, but I don't know why it is not included in deck.

The zip file contains three file, extract zip file and paste the file `AnkiDroid/collection.media`.

[MaterialIcons-Regular.zip](https://github.com/krmanik/Anki-xiehanzi/files/11107485/_MaterialIcons-Regular.zip)
