### ISSUE TITLE
What is the difference between the different HSK 3 decks?

### ISSUE THREAD

**Issue by lbench** [krmanik/Anki-xiehanzi#39]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by krmanik** [comment]
Read about deck type differences here. [Deck Types](https://github.com/krmanik/Anki-xiehanzi?tab=readme-ov-file#there-are-five-types-of-anki-xiehanzi-deck)
