### ISSUE TITLE
Writing feature not working on AnkiDroid

### ISSUE THREAD

**Issue by MangoTornado** [krmanik/Anki-xiehanzi#40]
**Describe the bug**
All other features of the deck work except for the writing plugin, on the latest version.
I have also tried hosting the library locally using termux.

![1000005137](https://github.com/krmanik/Anki-xiehanzi/assets/31556509/23b88824-30e9-40c0-aa79-971080c4a3a8)
![1000005138](https://github.com/krmanik/Anki-xiehanzi/assets/31556509/2a0673e2-e078-42cf-9d6f-bcb1484da42f)

 - Device: [OnePlus 11]
 - OS: [Android 13 (Oxygen OS 13.1)]
 - AnkiDroid Version [2.16.4]

**Comment by MangoTornado** [comment]
Nvm I'm stupid

**Comment by h4sh5** [comment]
@MangoTornado  how did you solve this issue?
