### ISSUE TITLE
To have separate toggles for front and back sides

### ISSUE THREAD

**Issue by leo150** [krmanik/Anki-xiehanzi#48]
**Is your feature request related to a problem? Please describe.**
I want to hide pinyin from the front side so I could recall it. I use the side menu toggle to hide it. However, I want to confirm that I memorized it correctly, so I still need to see pinyin on the back side. Currently, the toggle hides it for both sides.

**Describe the solution you'd like**
To have separate toggles for front and back sides.

<details>
  <summary>Screenshots</summary>
  
![Screenshot 2024-02-22 at 8 19 40 PM](https://github.com/krmanik/Anki-xiehanzi/assets/3484524/cf09be58-8e24-4735-a274-fe68cd7cb49d)
![Screenshot 2024-02-22 at 8 19 46 PM](https://github.com/krmanik/Anki-xiehanzi/assets/3484524/6c09501c-7db6-4e1a-8e15-d6b6daee3253)

</details>

**Comment by krmanik** [comment]
It can be added in next update. Can you try this deck and select `HSK 1::Pinyin`, it may solve your current issue?

https://ankiweb.net/shared/info/1351435439

[Read more](https://github.com/krmanik/Anki-xiehanzi?tab=readme-ov-file#type-1-recommended)

**Comment by leo150** [comment]
Oh, now I understand the structure. What I was looking for is indeed a "separate" deck. Thank you!
