### ISSUE TITLE
Menu icons not displaying, including when downloaded from GitHub releases

### ISSUE THREAD

**Issue by raviserota** [krmanik/Anki-xiehanzi#51]
**Describe the bug**
Menu icons (material) are missing from the deck

**To Reproduce**
1. Open deck
2. Flip card to back
3. Menu icons are not displayed

**Expected behavior**
Menu icons should be displayed

**Screenshots**
![image](https://github.com/krmanik/Anki-xiehanzi/assets/35924229/973b9215-70b9-48d5-a426-00864884165e)

**Desktop (please complete the following information):**
 - OS: macOS Apple Silicon
 - Browser: AnkiDesktop
 - Version 24.04

**Additional context**
I saw the previously closed issue reporting the same problem, but the issue #37  appears to still exist.

**Comment by krmanik** [comment]
The icon fonts are included, you can edit card template and paste this in styling at top, it will fix the issue. 

```
/* Material Icon Font */

@font-face {
  font-family: "Material Icons";
  font-style: normal;
  font-weight: 300;
  src: url(MaterialIcons-Regular.eot);
  /* For IE6-8 */
  src: local("Material Icons"), local("MaterialIcons-Regular"),
    url(_MaterialIcons-Regular.woff2) format("woff2"),
    url(_MaterialIcons-Regular.woff) format("woff"),
    url(https://fonts.gstatic.com/s/materialicons/v141/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2) format('woff2');
}
```

**Comment by krmanik** [comment]
It is fixed in https://github.com/krmanik/Anki-xiehanzi/commit/435c6eddac1f17718bcd4592f4f61b89e358a2c2
