### ISSUE TITLE
Unable to generate a deck through the create page

### ISSUE THREAD

**Issue by purp1edev** [krmanik/Anki-xiehanzi#55]
**Describe the bug**
After creating a deck, pressing the generate button does not do anything. The progress bar goes up to 100%, but then no file is downloaded or able to be saved. An error is also thrown in the console

**To Reproduce**
1. Go to 'https://krmanik.github.io/Anki-xiehanzi/create'
2. Enable Pinyin, English Definitions, and Writing Component
3. Go to next page
4. Add 好 to deck
5. Click 'Generate Deck'
6. Nothing happens and error is thrown in console

**Expected behavior**
An anki deck is generated that can be saved

**Error**
The error that is thrown in the console:
```
Uncaught (in promise) Error
    at r.handleError (2404.5fbd56b5.js:2:2460293)
    at r.prepare (2404.5fbd56b5.js:2:2459317)
    at v.write (2404.5fbd56b5.js:2:1599717)
    at v.writeToFile (2404.5fbd56b5.js:2:1599011)
    at 0fcd1e54.44bd1dff.js:1:86619
    at <anonymous>
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 124.0.6367.92

**Comment by krmanik** [comment]
Please try again, it is fixed now.

**Comment by purp1edev** [comment]
Working now, thanks!
