### ISSUE TITLE
Toggle function in Anki Mobile is really insensitive + Maobi Configuration doesn't work on Anki Mobile

### ISSUE THREAD

**Issue by Jessieyang13** [krmanik/Anki-xiehanzi#7]
Hello,

The app is spectacular by the way. I've learned how to write over 1000 characters with it, so thank you! 

I want to report an issue in hopes of improving it for the next update. 

1. The toggle function in Anki Mobile (iOS) doesn't really respond to me clicking it. The only one that kind of respond to my finger is the "Outline" option when I slide it. The rest (Simplified, Traditional, Pinyin, and Meaning) will only respond if I click on them continuously or get a bit creative with my clicking. Sometimes it works if I click around the slider or if I press it harder. Sometimes I have to restart my Anki Mobile. The "Stroke" and "Size" function at the bottom surprisingly works really well. There's no problem with the desktop version.

This is a picture of the toggle options.
![WechatIMG2034](https://user-images.githubusercontent.com/57219597/109749597-edc1f180-7c15-11eb-84b5-75cd74647d74.jpeg)

2. The Maobi configuration from the laptop version does not work on Anki Mobile. I have the configuration set to "show hint after 1 miss" but on Anki Mobile, it'll still take me 3 tries before the hint appears. I think the leniency setting doesn't work either but I can't be sure. The configuration works well on Anki desktop.

This is a picture of the configuration options. I accessed this from [edit] → [card] → [maobi].
![image](https://user-images.githubusercontent.com/57219597/109750086-c3246880-7c16-11eb-95ea-25245c581fee.png)

**Comment by infinyte7** [comment]
Hi, Anki-maobi and Anki-xiehanzi is different project implemented by different developer.
For issues related to Anki-maobi, you can submit issues here https://github.com/jcklie/anki-maobi
The developer @jcklie will help you.

**Comment by Jessieyang13** [comment]
Hello,

Sorry about that. I downloaded both projects so I may have gotten confused. I ended up with xiehanzi in the end since maobi doesn't integrate well with mobile. Anyway, I think the first problem/picture in my original post is still specific to xiehanzi.

**Comment by infinyte7** [comment]
Well, From pictures, I think you have to update deck html and css files.
And best way to update this by copy paste html and css to deck templates. **Do not download deck and import again.**
View this method.
https://github.com/infinyte7/Anki-xiehanzi/wiki/Update-xiehanzi-deck-on-AnkiDesktop

**Comment by Jessieyang13** [comment]
Updating by copy and pasting html and css to the deck templates helped! The buttons are still a bit clumsy, but they're working better than before. Thanks a bunch!

**Comment by krmanik** [comment]
After long time, I read the docs and found this
```
If you have other elements that must receive tap events, give them the class 'tappable' to tell AnkiMobile 2.0.39 or later that it should pass taps through to the element.
```

**Comment by krmanik** [comment]
The `tappable` class added to input and buttons.
