### ISSUE TITLE
Add an option to disable the X-shaped grid

### ISSUE THREAD

**Issue by Ross-Da-Boss** [krmanik/Anki-xiehanzi#9]
Hello,
Could you add an option (in the config menu for example) that could disable the X-shaped grid? (I'm talking about this one you can see behind the 休 character)
![image](https://user-images.githubusercontent.com/78878044/124130527-29af7b00-da7f-11eb-8c01-35a0dad07e34.png)
I'm not of a programmer so I'm too afraid to touch your code.

Thank you very much.

**Comment by infinyte7** [comment]
This will be implemented in next update.

**Comment by krmanik** [comment]
The xiehanzi v2 deck will be released soon with many fixes and features. The deck will be release in 2-3 days here and on Ankiweb.

**Comment by krmanik** [comment]
The features is added to latest version of deck.
